#ifndef KOMODO_CHAINPARAMSSEEDS_H
#define KOMODO_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the komodo network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[1] = {
    0
};

static SeedSpec6 pnSeed6_test[1] = {
    0
};
#endif // KOMODO_CHAINPARAMSSEEDS_H
